Repository TheThingsIndustries/generic-node-se, pull requests merged in 2021-04, with the labels that each got.

#162 doc: Add contribution guideline
  CONTRIBUTING.md
  README.md
Labels: doc

#169 lib: Fix tiny_tracer headers
  Software/lib/GNSE_TRACER/GNSE_tracer.h
  Software/lib/GNSE_TRACER/tiny_printf/tiny_printf.h
  Software/lib/GNSE_TRACER/tiny_printf/tiny_printf_conf.h
Labels: bug

#176 Doc/sch-bom-update
  CONTRIBUTING.md
  Hardware/fab/bom/pcb-bolink-batteryHolder.html
  Hardware/fab/bom/pcb-bolink-batteryHolder.xlsx
  Hardware/fab/bom/pcb-stm32wl.html
  Hardware/fab/bom/pcb-stm32wl.ods
  Hardware/fab/bom/pcb-stm32wl.xlsx
  Hardware/pcb-stm32wl/stm32wl.sch
Labels: discussion, documentation

#172 lib,app: Add downlink handler with buzzer tunes
  Software/app/README.md
  Software/app/basic_lorawan/lora_app.c
  Software/app/basic_lorawan/stm32wlxx_it.c
  Software/app/basic_lorawan/stm32wlxx_it.h
  Software/app/freefall_lorawan/conf/app_conf.h
  Software/app/freefall_lorawan/freefall.c
  Software/app/freefall_lorawan/freefall.h
  Software/app/freefall_lorawan/lora_app.c
  Software/app/freefall_lorawan/stm32wlxx_it.c
  Software/app/freefall_lorawan/stm32wlxx_it.h
  Software/app/freefall_lorawan/sys_app.c
  Software/lib/BUZZER/BUZZER.c
  Software/lib/GNSE_BSP/GNSE_bsp_clk_timer.c
  Software/lib/GNSE_BSP/GNSE_bsp_clk_timer.h
Labels: s/apps

#179 doc: Update documentation URL
  CONTRIBUTING.md
  Hardware/README.md
  README.md
  Software/README.md
Labels: doc, documentation
