Repository TheThingsIndustries/generic-node-se, pull requests merged in 2021-06, with the labels that each got.

#192 SE randomizer support
  .gitignore
  Software/lib/ATECC608A-TNGLORA/atecc608a-tnglora-se-hal.c
  Software/lib/ATECC608A-TNGLORA/atecc608a-tnglora-se.c
Labels: Firmware

#193 Flash double initialisation fix
  Software/lib/MX25R1635/MX25R16.c
  Software/lib/MX25R1635/MX25R16.h
  Software/lib/MX25R1635/mx_define.h
  Software/lib/MX25R1635/mx_test.h
  Software/lib/MX25R1635/mxic_hc.h
  Software/lib/MX25R1635/nor_cmd.h
  Software/lib/MX25R1635/nor_ops.h
  Software/lib/MX25R1635/spi.h
Labels: Firmware, bug

#195 doc: Add README for basic, basic_lorawan, freefall_lorawan apps
  Software/app/basic/README.md
  Software/app/basic_lorawan/README.md
  Software/app/freefall_lorawan/README.md
Labels: documentation

#198 app,dev: Add app_template application
  .gitignore
  Software/CMakeLists.txt
  Software/app/app_template/.cproject
  Software/app/app_template/.project
  Software/app/app_template/CMakeLists.txt
  Software/app/app_template/conf/app_conf.h
  Software/app/app_template/main.c
  Software/app/app_template/stm32wlxx_it.c
  Software/app/app_template/stm32wlxx_it.h
Labels: s/apps
