Repository TheThingsIndustries/generic-node-se, pull requests merged in 2021-07, with the labels that each got.

#205 Feature/GNSE_LPM
  Software/app/basic/.project
  Software/app/basic/conf/app_conf.h
  Software/app/basic_azurertos/.project
  Software/app/basic_bootloader/.project
  Software/app/basic_freertos/.project
  Software/app/basic_fuota/.project
  Software/app/basic_fuota/conf/app_conf.h
  Software/app/basic_fuota/lora_app.c
  Software/app/basic_fuota/main.c
  Software/app/basic_fuota/sys_app.c
  Software/app/basic_lorawan/.project
  Software/app/basic_lorawan/README.md
  Software/app/basic_lorawan/conf/app_conf.h
  Software/app/basic_lorawan/lora_app.c
  Software/app/basic_lorawan/main.c
  Software/app/basic_lorawan/sys_app.c
  Software/app/freefall_lorawan/.project
  Software/app/freefall_lorawan/README.md
  Software/app/freefall_lorawan/conf/app_conf.h
  Software/app/freefall_lorawan/freefall.c
  Software/app/freefall_lorawan/lora_app.c
  Software/app/freefall_lorawan/main.c
  Software/app/freefall_lorawan/sys_app.c
  Software/app/freertos_lorawan/CMakeLists.txt
  Software/app/freertos_lorawan/conf/app_conf.h
  Software/app/freertos_lorawan/sys_app.c
  Software/app/secure_element_lorawan/.project
  Software/app/secure_element_lorawan/conf/app_conf.h
  Software/app/secure_element_lorawan/lora_app.c
  Software/app/secure_element_lorawan/main.c
  Software/app/secure_element_lorawan/sys_app.c
  Software/app/sensors_lorawan/.project
  Software/app/sensors_lorawan/conf/app_conf.h
  Software/app/sensors_lorawan/lora_app.c
  Software/app/sensors_lorawan/main.c
  Software/app/sensors_lorawan/sys_app.c
  Software/lib/GNSE_BSP/GNSE_bsp_gpio.c
  Software/lib/GNSE_BSP/GNSE_bsp_gpio.h
  Software/lib/GNSE_HAL/GNSE_lpm.c
  Software/lib/GNSE_HAL/GNSE_lpm.h
  Software/lib/STM32WLxx_LoRaWAN/SubGHz_Phy/stm32_radio_driver/radio_driver.c
  Software/lib/Utilities/stm32_lpm.c
  Software/lib/Utilities/stm32_lpm.h
Labels: performance, scalability, sensors, technical debt

#211 doc: Add more application documentation
  CONTRIBUTING.md
  Docs/Images/generic_node_se.png
  Docs/Images/generic_node_se_stacked.png
  Docs/PinoutDiagram/GNSE_v1.1_pinout.png
  Docs/img_hw/GNSE_v1.1_pinout.png
  Docs/img_hw/generic_node_se.png
  Docs/img_hw/generic_node_se_stacked.png
  Docs/img_sw/stm32cubeide_linker_app.png
  Docs/img_sw/stm32cubeide_linker_bootloader.png
  README.md
  Software/app/README.md
  Software/app/app_template/README.md
  Software/app/basic_azurertos/README.md
  Software/app/basic_bootloader/README.md
  Software/app/basic_freertos/README.md
  Software/app/basic_fuota/README.md
  Software/app/freertos_lorawan/README.md
  Software/app/secure_element_lorawan/README.md
  Software/app/sensors_lorawan/README.md
  Software/app/sensors_lorawan/conf/app_conf.h
Labels: documentation

#212 Improve free fall application power consumption.
  Software/app/basic/basic_se_flash.c
  Software/app/freefall_lorawan/freefall.c
  Software/app/freefall_lorawan/sys_app.c
Labels: Firmware

#207 Generalized system clock call and error handler
  Software/app/basic/main.c
  Software/app/basic_bootloader/CMakeLists.txt
  Software/app/basic_bootloader/main.c
  Software/app/basic_fuota/main.c
  Software/app/basic_lorawan/main.c
  Software/app/freefall_lorawan/main.c
  Software/app/secure_element_lorawan/CMakeLists.txt
  Software/app/secure_element_lorawan/main.c
  Software/app/sensors_lorawan/main.c
  Software/lib/GNSE_HAL/GNSE_hal.c
  Software/lib/GNSE_HAL/GNSE_hal.h
Labels: Firmware
